CREATE TABLE [dbo].[Payments]
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PolicyId UNIQUEIDENTIFIER NOT NULL,
    Reference NVARCHAR(50) NOT NULL,
    Type INT NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_Payments_Policies FOREIGN KEY (PolicyId) REFERENCES Policies(Id) ON DELETE CASCADE
)
