CREATE TABLE [dbo].[Policyholders]
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PolicyId UNIQUEIDENTIFIER NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    DateOfBirth DATE NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSUTCDATETIME(),
    LastModifiedAt DATETIMEOFFSET NULL,
    CONSTRAINT FK_Policyholders_Policies FOREIGN KEY (PolicyId) REFERENCES Policies(Id) ON DELETE CASCADE
)
