CREATE TABLE [dbo].[Properties]
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PolicyId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    AddressLine1 NVARCHAR(255) NOT NULL,
    AddressLine2 NVARCHAR(255) NULL,
    AddressLine3 NVARCHAR(255) NULL,
    Postcode NVARCHAR(8) NOT NULL,
    CreatedDate DATETIMEOFFSET NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Properties_Policies FOREIGN KEY (PolicyId) REFERENCES Policies(Id) ON DELETE CASCADE
);